module(name = "integration_test")

bazel_dep(name = "package_metadata", version = "0.0.7")
bazel_dep(name = "rules_python", version = "0.0.0")
local_path_override(
    module_name = "rules_python",
    path = "../../..",
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.14",
)
use_repo(python, pbs_host = "python_3_14_host")

pip_archive = use_repo_rule("@rules_python//python/private/pypi:whl_library.bzl", "pip_archive")

pip_archive(
    name = "pip_sdist_archive",
    filename = "requests-2.34.2.tar.gz",
    python_interpreter_target = "@pbs_host//:python",
    requirement = "requests",
    # https://pypi.org/project/requests/#requests-2.34.2.tar.gz
    sha256 = "f288924cae4e29463698d6d60bc6a4da69c89185ad1e0bcc4104f584e960b9ed",
    urls = [
        "https://files.pythonhosted.org/packages/ac/c3/e2a2b89f2d3e2179abd6d00ebd70bff6273f37fb3e0cc209f48b39d00cbf/requests-2.34.2.tar.gz",
    ],
)

pip_archive(
    name = "pip_archive",
    python_interpreter_target = "@pbs_host//:python",
    requirement = "requests",
)

whl_archive = use_repo_rule("@rules_python//python/private/pypi:whl_library.bzl", "whl_archive")

whl_archive(
    name = "whl_archive",
    dep_template = "@integration_test//:{name}_{target}",
    filename = "requests-2.34.2-py3-none-any.whl",
    # https://pypi.org/project/requests/#requests-2.34.2-py3-none-any.whl
    requirement = "requests",
    sha256 = "2a0d60c172f83ac6ab31e4554906c0f3b3588d37b5cb939b1c061f4907e278e0",
    urls = [
        "https://files.pythonhosted.org/packages/a0/f4/c67b0b3f1b9245e8d266f0f112c500d50e5b4e83cb6f3b71b6528104182a/requests-2.34.2-py3-none-any.whl",
    ],
)

whl_deps_library = use_repo_rule("@rules_python//python/private/pypi:whl_library.bzl", "whl_deps_library")

whl_deps_library(
    name = "whl_deps_library",
    dep_template = "@integration_test//:{name}_{target}",
    metadata_file = "@whl_archive//:metadata.json",
)
