#!/usr/bin/env python3

"""Synchronizes runtimes_manifest_workspace.bzl with runtimes_manifest.txt."""

import argparse
import sys
from pathlib import Path


def sync_workspace_manifest(txt_path: Path, bzl_path: Path) -> bool:
    with open(txt_path, "r", encoding="utf-8") as f:
        txt_content = f.read()
    header = '''"""Manifest of runtimes for workspace mode builds.

This is the workspace equivalent of runtimes_manifest.txt. It's a bzl file
to simplify loading of the data under workspace mode, which doesn't
support parsing a runtimes_manifest.txt file.

NOTE: This file is automatically generated by sync_runtimes_manifest_workspace.py.
Do not edit directly!
"""

MANIFEST_TEXT = """
'''

    new_content = header + txt_content + '"""\n'

    if bzl_path.exists():
        with open(bzl_path, "r", encoding="utf-8") as f:
            old_content = f.read()
    else:
        old_content = ""

    if new_content != old_content:
        with open(bzl_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(new_content)
        return True

    return False


def main():
    parser = argparse.ArgumentParser(
        description="Sync runtimes workspace bzl file with runtimes manifest text file."
    )
    parser.add_argument(
        "txt_path",
        nargs="?",
        type=Path,
        help="Path to runtimes_manifest.txt",
    )
    parser.add_argument(
        "bzl_path",
        nargs="?",
        type=Path,
        help="Path to runtimes_manifest_workspace.bzl",
    )
    args = parser.parse_args()

    txt_path = args.txt_path
    bzl_path = args.bzl_path

    if not txt_path or not bzl_path:
        repo_root = Path(__file__).resolve().parent.parent.parent.parent
        txt_path = repo_root / "python" / "private" / "runtimes_manifest.txt"
        bzl_path = repo_root / "python" / "private" / "runtimes_manifest_workspace.bzl"

    if not txt_path.exists():
        print(f"Error: Manifest not found: {txt_path}", file=sys.stderr)
        sys.exit(1)

    if sync_workspace_manifest(txt_path, bzl_path):
        print(f"Updated {bzl_path}")
        if not args.bzl_path:
            # Exit 1 for pre-commit mode (in-place modification)
            sys.exit(1)


if __name__ == "__main__":
    main()
