load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//python/private:distribution_filegroup.bzl", "distribution_filegroup")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

distribution_filegroup(
    name = "distribution",
)

bzl_library(
    name = "py_zipapp_binary",
    srcs = ["py_zipapp_binary.bzl"],
    deps = [
        "//python/private:util",
        "//python/private/zipapp:py_zipapp_rule",
    ],
)

# keep
bzl_library(
    name = "py_zipapp_test",
    srcs = ["py_zipapp_test.bzl"],
    deps = [
        "//python/private:util",
        "//python/private/zipapp:py_zipapp_rule",
    ],
)
