load("//python:py_binary.bzl", "py_binary")
load("//python:py_library.bzl", "py_library")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "changelog_news",
    srcs = ["changelog_news.py"],
    imports = ["../.."],
)

py_library(
    name = "release_lib",
    srcs = glob(
        ["*.py"],
        exclude = [
            "changelog_news.py",
            "mock_gh.py",
        ],
    ),
    imports = ["../.."],
    deps = [
        ":changelog_news",
        "@dev_pip//packaging",
    ],
)

py_library(
    name = "mock_gh",
    srcs = ["mock_gh.py"],
    imports = ["../.."],
    deps = [
        ":release_lib",
    ],
)

py_binary(
    name = "release",
    srcs = ["release.py"],
    imports = ["../.."],
    main = "release.py",
    python_version = "3.14",
    deps = [
        ":release_lib",
    ],
)
