local_repository(
    name = "rules_python",
    path = "../../..",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python3_11",
    python_version = "3.11",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip_empty",
    python_interpreter_target = "@python3_11_host//:python",
    requirements_lock = "//empty:requirements.txt",
)

load("@pip_empty//:requirements.bzl", "install_deps")

install_deps()
