#!/usr/bin/env bash
# Generated by rules_python py_zipapp_binary
# This launcher script is for non-sandboxed execution only.
# Within Bazel's sandbox, the zipapp is intended to be executed directly by Python.
# See https://docs.python.org/3/library/zipapp.html

INTERPRETER="$(rlocation %interpreter_rloc%)"
ZIPFILE="$(rlocation %zip_file_rloc%)"

# Execute the zipapp using the Python interpreter
"${INTERPRETER}" "${ZIPFILE}" "$@"
