load("@rules_python//python/uv:lock.bzl", "lock")

package(default_visibility = ["//:__subpackages__"])

filegroup(
    name = "distribution",
    srcs = glob(["**/*"]),
    visibility = ["//:__pkg__"],
)

# Run bazel run //dev:uv_lock.update
lock(
    name = "uv_lock",
    srcs = ["//:pyproject.toml"],
    out = "uv.lock",
    python_version = "3.11",
)

# Run bazel run //dev:requirements.update
lock(
    name = "requirements",
    srcs = ["//:pyproject.toml"],
    out = "requirements.txt",
    args = [
        "--emit-index-url",
        "--universal",
        "--upgrade",
    ],
    python_version = "3.11",
)
