load("@rules_python//python/uv:lock.bzl", "lock")

lock(
    name = "requirements_3_10",
    srcs = ["pyproject.toml"],
    out = "requirements_lock_3_10.txt",
    args = [
        "--emit-index-url",
        "--universal",
        "--python-version=3.10",
    ],
    python_version = "3.10",
)

lock(
    name = "requirements_3_11",
    srcs = ["pyproject.toml"],
    out = "requirements_lock_3_11.txt",
    args = [
        "--emit-index-url",
        "--universal",
        "--python-version=3.11",
    ],
    python_version = "3.11",
)

lock(
    name = "requirements_3_12",
    srcs = ["pyproject.toml"],
    out = "requirements_lock_3_12.txt",
    args = [
        "--emit-index-url",
        "--universal",
        "--python-version=3.12",
    ],
    python_version = "3.12",
)

lock(
    name = "requirements_3_13",
    srcs = ["pyproject.toml"],
    out = "requirements_lock_3_13.txt",
    args = [
        "--emit-index-url",
        "--universal",
        "--python-version=3.13",
    ],
    python_version = "3.13",
)

lock(
    name = "requirements_3_14",
    srcs = ["pyproject.toml"],
    out = "requirements_lock_3_14.txt",
    args = [
        "--emit-index-url",
        "--universal",
        "--python-version=3.14",
    ],
    python_version = "3.14",
)
