load("//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")
load("//python/private:distribution_filegroup.bzl", "distribution_filegroup")  # buildifier: disable=bzl-visibility
load("//tools/private:publish_deps.bzl", "publish_deps")

package(default_visibility = ["//:__subpackages__"])

py_console_script_binary(
    name = "twine",
    # We transition to a specific python version in order to ensure that we
    # don't rely on the default version configured by the root module.
    pkg = "@rules_python_publish_deps//twine",
    python_version = "3.11",
    script = "twine",
    visibility = ["//visibility:public"],
)

distribution_filegroup(
    name = "distribution",
)

# Run bazel run //private:requirements.update to update the outs
publish_deps(
    name = "requirements",
    srcs = ["pyproject.toml"],
    outs = {
        "requirements_darwin.txt": "macos",
        "requirements_linux.txt": "linux",
        "requirements_universal.txt": "",  # universal
        "requirements_windows.txt": "windows",
    },
    args = [
        "--emit-index-url",
        "--upgrade",  # always upgrade
    ],
    visibility = ["//private:__pkg__"],
)
