load("@rules_multirun//:defs.bzl", "multirun")

# This file has various targets that are using dev-only dependencies that our users should not ideally see.

multirun(
    name = "requirements.update",
    commands = [
        "//tools/publish:{}.update".format(r)
        for r in [
            "requirements_universal",
            "requirements_darwin",
            "requirements_windows",
            "requirements_linux",
        ]
    ] + [
        "//dev:requirements.update",
        "//dev:uv_lock.update",
        "//examples:bzlmod_requirements_3_12.update",
        "//examples:bzlmod_requirements_3_12_windows.update",
        "//examples:bzlmod_requirements_3_13.update",
        "//examples:bzlmod_requirements_3_13_windows.update",
        "//examples:bzlmod_requirements_3_14.update",
        "//examples:bzlmod_requirements_3_14_windows.update",
        "//tests/multi_pypi/alpha:requirements.update",
        "//tests/multi_pypi/beta:requirements.update",
        "//tests/uv/lock/pyproject_toml:requirements.update",
        "//tests/uv/lock/workspaces:requirements.update",
    ],
    tags = ["manual"],
)

# NOTE: The requirements for the pip dependencies may sometimes break the build
# process due to how `pip-compile` works (i.e. it sometimes needs to build
# wheels to resolve the `pyproject.toml` file.  Hence we do not lump the
# target with the other targets above.
alias(
    name = "whl_library_requirements.update",
    actual = "//tools/private/update_deps:update_pip_deps",
    tags = ["manual"],
)
